config/routes.rb
Rails.application.routes.draw do
  get 'shows/index'

  get 'channels/index'

  get 'welcome/index'

  get 'welcome/index'
    resources :channels
    resources :favorites
    resources :shows
  root 'welcome#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	has_many :shows
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	has_many :shows
end

app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :channel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
  	@channels = Channel.all
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
  	@shows = Show.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@favorites	= Favorite.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channeles_helper.rb
module ChannelesHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/channels/index.html.erb
<h1>Listing Channels</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Frequency</th>
    <th></th>
  </tr>
 
  <% @channels.each do |channel| %>
    <tr>
      <td><%= channel.name %></td>
      <td><%= channel.frequency %></td>
      <td><%= link_to 'Tv_show', shows_path %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TvShow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', root_path %> || <%= link_to 'Channel', channels_path %> || <%= link_to 'shows', shows_path %> || <%= link_to 'My Favorate', favorites_path %>
<%= yield %>

</body>
</html>

app/views/shows/index.html.erb
<h1>Listing TV Shows</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Time</th>
    <th>Channel </th>
  </tr>
 
  <% @shows.each do |show| %>
    <tr>
      <td><%= show.show_title %></td>
      <td><%= show.time %></td>
      <td><%channal = show.channel_id %>
      	<%= Channel.find(channal).name %>
      </td>
      <td><%#= link_to 'favorate', method: :post, favorites_path(show.id) %>
      	<%#= link_to 'favorate', favorites_path(show.id),
              method: "post" %>
        <%= link_to "favorate", favorites_path(show_id: show.id), :method=> :post %>      
      </td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<center><h1>Welcome to TV Show</h1></center><br>
<%= link_to 'Channel', channels_path %> || <%= link_to 'shows', shows_path %>

<h1> MY favarote </h1><br>

<% @favorites.each do |fav| %>
    <tr>
      <td>
      	<%= Show.find(fav.show_id).show_title %><br>
      </td>
      <td><%#= show.time %></td>
     
      </td>
    </tr>
  <% end %>